version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vm-teste-tecnico
    container_name: vm-teste-api
    restart: unless-stopped
    depends_on:
      - postgres
      - mailhog
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vmtech_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_APPLICATION_NAME=vm-teste-tecnico
      - SPRING_MAIL_USERNAME=vmtech.teste@gmail.com
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
      - JWT_SECRET=Ab1!Xy9@Lu3#Pq7^ZrLm*Go2$TxQ
      - JWT_EXPIRATION=86400000
    networks:
      - backend-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vmtech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: